/* KINGDOMS MVP — настройки Firebase см. README.txt */
const firebaseConfig={apiKey:"PASTE_API_KEY_HERE",authDomain:"PASTE_PROJECT_ID_HERE.firebaseapp.com",databaseURL:"https://PASTE_PROJECT_ID_HERE-default-rtdb.firebaseio.com",projectId:"PASTE_PROJECT_ID_HERE",appId:"PASTE_APP_ID_HERE"};
const $=id=>document.getElementById(id);
const B={woodcutter:{n:"Лесопилка",i:"🪵",w:35,s:0,d:"Производит 2 дерева каждые 10 секунд."},quarry:{n:"Каменоломня",i:"🪨",w:25,s:15,d:"Производит 1 камень каждые 10 секунд."},farm:{n:"Ферма",i:"🌾",w:30,s:0,d:"Производит 4 еды каждые 10 секунд."},bakery:{n:"Пекарня",i:"🍞",w:25,s:10,d:"Дополнительно производит 3 еды каждые 10 секунд."},barracks:{n:"Казармы",i:"⚔️",w:45,s:25,d:"Открывают найм пехоты."},wall:{n:"Стена",i:"🧱",w:10,s:15,d:"Укрепляет оборону крепости."},market:{n:"Рынок",i:"🏪",w:35,s:10,d:"Производит 1 золото каждые 10 секунд."}};
let db,uid,roomCodeNow="",myName="",data=null,chosen=null,unsub=null,busy=false,lastTick=0;
function ready(){return firebaseConfig.apiKey!=="PASTE_API_KEY_HERE"&&firebaseConfig.projectId!=="PASTE_PROJECT_ID_HERE"}
function say(t){$("lobbyStatus").textContent=t}function toast(t){let e=$("toast");e.textContent=t;e.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add("hidden"),2600)}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function nameClean(s){return(s||"Правитель").trim().replace(/[.#$\[\]/]/g,"").slice(0,18)||"Правитель"}
function template(n){return{name:n,wood:120,stone:80,food:150,gold:80,people:12,troops:5,score:0,buildings:{"4_4":{type:"keep",level:1}}}}
function newRoom(code){return{code,createdAt:Date.now(),players:{},log:["Партия создана"]}}
function logAdd(r,t){r.log=r.log||[];r.log.unshift(t);r.log=r.log.slice(0,15)}
function me(){return data?.players?.[uid]}
function firebaseCheck(){if(!ready()){say("Настрой Firebase по README.txt — без этого общая игра не подключится.");return false}return true}
async function init(){if(!firebaseCheck())return;try{firebase.initializeApp(firebaseConfig);await firebase.auth().signInAnonymously();uid=firebase.auth().currentUser.uid;db=firebase.database();say("Сеть подключена. Создай партию или введи код комнаты.")}catch(e){say("Ошибка Firebase: "+e.message);console.error(e)}}
async function create(){if(!firebaseCheck()||busy)return;busy=true;try{myName=nameClean($("playerName").value);let code=Math.random().toString(36).slice(2,7).toUpperCase(),r=newRoom(code);r.players[uid]=template(myName);let res=await db.ref("rooms/"+code).transaction(old=>old===null?r:undefined);if(!res.committed)throw Error("Не удалось создать комнату. Попробуй ещё раз.");await enter(code)}catch(e){say(e.message)}finally{busy=false}}
async function join(){if(!firebaseCheck()||busy)return;busy=true;try{myName=nameClean($("playerName").value);let code=$("roomCode").value.trim().toUpperCase();if(!/^[A-Z0-9]{5}$/.test(code))throw Error("Код должен содержать 5 латинских букв или цифр.");let res=await db.ref("rooms/"+code).transaction(r=>{if(!r)return;r.players=r.players||{};if(r.players[uid]){r.players[uid].name=myName;return r}if(Object.keys(r.players).length>=5)return;r.players[uid]=template(myName);logAdd(r,myName+" присоединился к партии");return r});if(!res.committed)throw Error("Комната не найдена или уже заполнена (5/5).");await enter(code)}catch(e){say(e.message)}finally{busy=false}}
async function enter(code){if(unsub)unsub();roomCodeNow=code;let ref=db.ref("rooms/"+code),s=await ref.get();if(!s.exists())throw Error("Комната не найдена");data=s.val();$("lobby").classList.add("hidden");$("game").classList.remove("hidden");$("roomLabel").textContent=code;unsub=ref.on("value",s=>{if(!s.exists())return;data=s.val();render()});startProduction()}
async function change(fn,logText){if(!db||!roomCodeNow||busy)return;busy=true;try{let res=await db.ref("rooms/"+roomCodeNow).transaction(r=>{if(!r?.players?.[uid])return;let p=r.players[uid];if(fn(p,r)===false)return;p.lastAction=Date.now();if(logText)logAdd(r,typeof logText==="function"?logText(p,r):logText);return r});if(!res.committed)toast("Не удалось выполнить действие — проверь ресурсы.")}catch(e){toast("Ошибка сети: "+e.message)}finally{busy=false}}
async function build(x,y){if(!chosen)return toast("Сначала выбери здание.");let type=chosen,b=B[type],key=x+"_"+y;if(me().buildings?.[key])return toast("Клетка занята.");await change(p=>{p.buildings=p.buildings||{};if(p.buildings[key]||p.wood<b.w||p.stone<b.s)return false;p.wood-=b.w;p.stone-=b.s;p.buildings[key]={type,level:1};p.score=(p.score||0)+10;return true},()=>myName+" построил: "+b.n);chosen=null;renderBuildings()}
async function recruit(){await change(p=>{if(!Object.values(p.buildings||{}).some(b=>b.type==="barracks")){toast("Сначала построй казармы.");return false}if(p.food<10||p.gold<5){toast("Нужно 10 еды и 5 золота.");return false}p.food-=10;p.gold-=5;p.troops++;return true},()=>myName+" обучил пехотинца")}
async function attack(){let target=$("targetPlayer").value;if(!target)return toast("Выбери цель.");let enemy=data.players[target],p=me();if(!enemy)return;if(p.troops<3)return toast("Для рейда нужно минимум 3 воина.");if(p.food<15)return toast("Нужно 15 еды для похода.");let win=p.troops*10+Math.random()*20>(enemy.troops||0)*10+Object.values(enemy.buildings||{}).filter(b=>b.type==="wall").length*7+Math.random()*20;let outcome=win?"Победа над "+enemy.name+"!":"Рейд против "+enemy.name+" отражён.";await change((me,r)=>{let foe=r.players[target];if(!foe||me.troops<3||me.food<15)return false;me.food-=15;me.troops=Math.max(0,me.troops-(win?1:2));if(win){let w=Math.min(25,foe.wood||0),f=Math.min(20,foe.food||0),g=Math.min(10,foe.gold||0);foe.wood-=w;foe.food-=f;foe.gold-=g;me.wood+=w;me.food+=f;me.gold+=g}else foe.troops=Math.max(0,(foe.troops||0)-1);logAdd(r,myName+" атаковал "+foe.name+". "+outcome);return true});$("armyStatus").textContent=outcome;toast(outcome)}
function startProduction(){if(startProduction.timer)clearInterval(startProduction.timer);startProduction.timer=setInterval(async()=>{if(!db||!roomCodeNow||busy||Date.now()-lastTick<9000)return;lastTick=Date.now();await change(p=>{let a=Object.values(p.buildings||{}),n=t=>a.filter(b=>b.type===t).length;p.wood+=n("woodcutter")*2;p.stone+=n("quarry");p.food+=n("farm")*4+n("bakery")*3;p.gold+=n("market");p.food=Math.max(0,p.food-Math.ceil((p.people||0)/10));p.score=(p.score||0)+1;return true})},10000)}
function render(){let p=me();if(!p)return;["wood","stone","food","gold","people","troops"].forEach(k=>$(k).textContent=Math.floor(p[k]||0));let ids=Object.keys(data.players||{});$("playerCount").textContent=ids.length+"/5";$("playerList").innerHTML=ids.map(id=>{let v=data.players[id];return `<div class="player ${id===uid?'me':''}"><span>${id===uid?'👑 ':''}${safe(v.name)}${id===uid?' (ты)':''}<br><small>🏰 ${Object.keys(v.buildings||{}).length} строений · ⚔ ${v.troops||0}</small></span><b>${v.score||0} очк.</b></div>`}).join("");let old=$("targetPlayer").value;$("targetPlayer").innerHTML='<option value="">Выбери игрока…</option>'+ids.filter(id=>id!==uid).map(id=>`<option value="${id}">${safe(data.players[id].name)} · ${data.players[id].troops||0} воинов</option>`).join("");if(ids.includes(old)&&old!==uid)$("targetPlayer").value=old;renderMap()}
function renderMap(){let p=me();if(!p)return;let map=$("castleMap");map.innerHTML="";for(let y=0;y<9;y++)for(let x=0;x<9;x++){let key=x+"_"+y,b=p.buildings?.[key],e=document.createElement("button");e.className="tile "+(b?(b.type==="keep"?"castle":b.type==="wall"?"wall":""):"");e.type="button";e.innerHTML=b?B[b.type]?B[b.type].i+'<span class="lv">ур. 1</span>':'🏰':' ';if(b?.type==="keep")e.innerHTML='🏰<span class="lv">ур. 1</span>';e.onclick=()=>b?toast((B[b.type]?.n||"Крепость")+" — "+(B[b.type]?.d||"Центр королевства.")):build(x,y);map.appendChild(e)}}
function renderBuildings(){let list=$("buildingList");list.innerHTML="";Object.entries(B).forEach(([type,b])=>{let e=document.createElement("button");e.className="build-option"+(chosen===type?" active":"");e.innerHTML=`<span class="ico">${b.i}</span><span><strong>${b.n}</strong><small>🪵 ${b.w} · 🪨 ${b.s}</small></span>`;e.onclick=()=>{chosen=chosen===type?null:type;renderBuildings();$("selectedBuilding").textContent=chosen?b.d+" Нажми на свободную клетку.":"Выбери постройку, затем свободную клетку."};list.appendChild(e)})}
$("createRoom").onclick=create;$("joinRoom").onclick=join;$("roomCode").oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,5);$("recruit").onclick=recruit;$("attack").onclick=attack;$("copyInvite").onclick=async()=>{try{await navigator.clipboard.writeText(roomCodeNow);toast("Код "+roomCodeNow+" скопирован")}catch(e){prompt("Скопируй код комнаты",roomCodeNow)}};renderBuildings();init();
